# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-bcellmagic-1.3.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.11
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.9
  - matplotlib=3.0.3
  - conda-forge::unzip=6.0
  - conda-forge::zip=3.0