name: nf-core-bcellmagic-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - fastqc=0.11.8
  - multiqc=1.6
  - muscle=3.8.1551
  - vsearch=2.11.1
  - cd-hit=4.8.1
  - blast=2.7.1
  - igblast=1.10.0
  - phylip=3.697
  - tbl2asn=25.6
  - airr=1.2.1
  - r-airr=1.2.0
  - presto=0.5.10
  - changeo=0.4.5
  - conda-forge::r-alakazam=0.2.11
  - r-shazam=0.1.10
  - r-tigger=0.3.1
  - python=3.6.7 # the current one would be 3.7.3, but changeo complains
  - biopython=1.73
