# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-bcellmagic-1.3.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.11
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - muscle=3.8.1551
  - vsearch=2.11.1
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.9
  - matplotlib=3.0.3
  - cd-hit=4.8.1
  - igblast=1.15.0
  - phylip=3.697
  - tbl2asn=25.6
  - presto=0.6.2
  - bioconda::changeo=1.0.1
  - conda-forge::unzip=6.0
  - conda-forge::zip=3.0
  - conda-forge::ghostscript=9.22
  #- conda-forge::pandas=0.24.2
  #- conda-forge::seaborn=0.9.0
  #- conda-forge::cairo=1.16.0
  - conda-forge::mscorefonts=0.0.1
  - bioconda::phylip=3.697
  - conda-forge::r-base=4.0.3
  - conda-forge::r-alakazam=1.0.2
  - conda-forge::r-shazam=1.0.2
  - conda-forge::r-tigger=1.0.0
  #- conda-forge::r-dplyr=1.0.3
  #- conda-forge::r-data.table=1.13.6
  #- conda-forge::r-igraph=1.2.6
  #- conda-forge::r-gplots=3.1.1
  #- conda-forge::r-circlize=0.4.12
  #- conda-forge::r-upsetr=1.4.0
  #- conda-forge::r-gtools=3.8.1
  - conda-forge::r-ggplot2=3.3.3
  #- conda-forge::r-svglite=1.2.3
  #- conda-forge::r-extrafont=0.17
  - conda-forge::r-optparse=1.6.6
  #- r-airr=1.2.0

