# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-bcellmagic-immcantation-1.3.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::unzip=6.0
  - conda-forge::zip=3.0
  - conda-forge::cairo=1.16.0
  - conda-forge::mscorefonts=0.0.1
  - bioconda::phylip=3.697
  - bioconda::presto=0.6.0
  - bioconda::changeo=1.0.1
  - bioconda::biopython=1.70
  - bioconda::muscle=3.8.1551
  - bioconda::vsearch=2.15.1
  - bioconda::igblast=1.15.0
  - bioconda::cd-hit=4.8.1
  - conda-forge::ghostscript=9.53.3
  - conda-forge::r-base=4.0.3
  - conda-forge::r-alakazam=1.0.2
  - conda-forge::r-shazam=1.0.2
  - conda-forge::r-tigger=1.0.0
  - conda-forge::r-dplyr=1.0.3
  - conda-forge::r-data.table=1.13.6
  - conda-forge::r-igraph=1.2.6
  - conda-forge::r-gplots=3.1.1
  - conda-forge::r-circlize=0.4.12
  - conda-forge::r-upsetr=1.4.0
  - conda-forge::r-gtools=3.8.2
  - conda-forge::r-ggplot2=3.3.3
  - conda-forge::r-svglite=1.2.3.2
  - conda-forge::r-extrafont=0.17
  - conda-forge::r-optparse=1.6.6
  - r-airr=1.3.0

